# .github/workflows/A.yml

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Load env
      id: load-env
      uses: mshick/env-cmd-exec-action@v1
      with:
        include: env.yml
            
    - name: Use env vars
      run: |
        echo $FOO
        echo $BAZ
