# .github/workflows/workflow.yml

name: My Workflow

on: 
  push:
    branches: 
      - main

env:
  include: env.yml
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout 
      uses: actions/checkout@v4
    
      
    - name: Print env vars
      run: |
        echo $FOO 
        echo $BAZ
