# .github/workflows/workflow.yml

name: My Workflow

on: push

env:
  include: env.yml
  
jobs:

  my_job:
    name: My Job
    runs-on: ubuntu-latest
    
    steps:
    - name: Print env vars
      run: |
        echo $FOO 
        echo $BAZ
