name: Use Environment Variables

on:
  push:
    branches:
      - main

jobs:
  use-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: env-vars

      - name: Use Variables
        run: |
          echo "Value from B: $(cat env-vars/env-vars.txt)"
