name: Set Environment Variables

on:
  push:
    branches:
      - main

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    outputs:
      env-vars: ${{ steps.set-vars.outputs.env-vars }}

    steps:
      - name: Set Variables
        id: set-vars
        run: |
          echo "env-vars=VALUE_FROM_B" >> $GITHUB_ENV
